spring:
  application:
    name: lootopia-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/project_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

file:
  upload-dir: C:\Users\Mohamed-work\Desktop\lootopia-uploads

stripe:
  secret:
    key: sk_test_
  success:
    url: http://localhost:4200/app/market/success
  cancel:
    url: http://localhost:4200/app/market/canceled
  webhook:
    secret: whsec_
